server:
  port: 7001
spring:
  application:
    name: cloud-eureka-service
eureka:
  instance:
    # eureka服务端的实例名称
    hostname: eureka7001.com
    #访问路劲可显示IP地址
    prefer-ip-address: true


  client:
    # false表示不向注册中心注册自己
    register-with-eureka: false
    # false表示自己端就是注册中心,我的职责就是维护服务实例,并不需要检索服务
    fetch-registry: false
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址
      #defaultZone: http://eureka7002.com:7002/eurake/
      defaultZone: http://eureka7001.com:7001/eurake/
  server:
    #自我保护机制
    #enable-self-preservation: true
    #自我保护的保留时间
    #eviction-interval-timer-in-ms: 9000

